name: 'Fetch RUM Insights for experiment'
description: 'Fetch RUM insights for experiment'
inputs:
  domain:
    description: The website domain to fetch the RUM insights from
    required: true
  domain-key:
    description: The domainKey for accessing the domain RUM data
    required: true
  days:
    description: The number of days to get the data
    required: false
    default: 30
outputs:
  data: # id of output
    description: 'A JSON object represneting the RUM data organized by page and experiment'
runs:
  using: 'node20'
  main: 'dist/index.js'